services:
  nvidia_pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    image: nvcr.io/nvidia/pytorch:22.10-py3
    # コンテナ名を明示的に指定する
    # container_name: nvidia_pytorch-container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/home/Pokemon-SV-Detection
      - ../Pokemon-SV-Datasets:/home/Pokemon-SV-Datasets
    ports:
      - "6666:6666"
    # command:
    #   jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --port=6666
    #   # nvidia-smi
    
    tty:
      true